Tuedontuoyo/get 18 navigation and desktop layout for
getnshare/frontend pull request #5
Opened 2022-01-01 20:49 UTC by 0tuedon

I design the landing page as me and @asapconet  discuss if there is any other thing you would like me to add please do. 
![Screenshot (265)](https://user-images.githubusercontent.com/90271995/147859913-602e02b7-c7dd-4bd3-9ac8-7286dbc58f17.png)
The above is the design for the landing page coded and responsive

2022-01-02 12:19 UTC, 0tuedon commented
![Screenshot (270)](https://user-images.githubusercontent.com/90271995/147875474-5d5a58f0-d8b1-4568-a689-7ffc75588501.png)
The new Ui

2022-01-02 21:34 UTC, Eronmmer commented
<img width="358" alt="Screenshot 2022-01-02 at 22 25 47" src="https://user-images.githubusercontent.com/37238033/147889929-b4d3767c-cee8-40e0-9b82-31c6d9ac46a2.png">

@0tuedon please be consistent with casing for outer-level folders
All the folders under another folder or directory should use the same case. In the screenshot above, `Components`, `Pages`, and `utils` should either be in lowercase or uppercase

2022-01-02 21:40 UTC, Eronmmer commented
<img width="354" alt="Screenshot 2022-01-02 at 22 35 25" src="https://user-images.githubusercontent.com/37238033/147890092-ae0e2951-32f5-41c9-a8ec-16915c804de6.png">

An image shouldn't be in a `utils` folder. Move all images to `/public/assets`. 
Ideally, a `utils` folder should contain utility, reusable functions, constants, classes, and other blocks of code that can be reused  more than once in the codebase

2022-01-02 21:47 UTC, Eronmmer commented
<img width="627" alt="Screenshot 2022-01-02 at 22 43 21" src="https://user-images.githubusercontent.com/37238033/147890242-8ff7d2ed-9956-4116-b80d-2b848f3518ea.png">

Some suggestions
- Increase the border of the input element here
- Add some margin between the input element and the button
- Give the button some life
  - Add more padding
  - Change the color to something like yellow?
- Add some margin after the 'Get Early Access' input label

2022-01-02 21:50 UTC, Eronmmer commented
<img width="1440" alt="Screenshot 2022-01-02 at 22 47 55" src="https://user-images.githubusercontent.com/37238033/147890312-364f2de3-7458-415c-91a9-5724bbbcb188.png">

@0tuedon  I think you should add some padding to the navigation links. You may want to reduce the margin between the two social icons on the top right. You may also want to increase the font size of the 'GetnShare' header on the top left

2022-01-02 21:53 UTC, Eronmmer requested changes

2022-01-02 21:53 UTC, Eronmmer commented on src/Components/Button.js
> +      <button className="bg-white  shadow-md px-9  hover:bg-amber-400 py-4 rounded-3xl border-slate-400">
@0tuedon @asapconet, you can check the comments I dropped in this PR for the requested changes

2022-01-03 16:48 UTC, 0tuedon commented
![Screenshot (281)](https://user-images.githubusercontent.com/90271995/147956873-a651f338-15f9-43e7-a304-0907fda229ca.png)
Folder structure done
![Screenshot (282)](https://user-images.githubusercontent.com/90271995/147956883-949fe3b4-8f0f-4b2e-a3f7-57ec80f4ea70.png)
And i have  reworked the ui of the landing page 
@Eronmmer

2022-01-03 16:57 UTC, 0tuedon commented
> <img alt="Screenshot 2022-01-02 at 22 47 55" width="1440" src="https://user-images.githubusercontent.com/37238033/147890312-364f2de3-7458-415c-91a9-5724bbbcb188.png">
> 
> @0tuedon I think you should add some padding to the navigation links. You may want to reduce the margin between the two social icons on the top right. You may also want to increase the font size of the 'GetnShare' header on the top left

Okay will do

2022-01-03 17:56 UTC, 0tuedon commented
> <img alt="Screenshot 2022-01-02 at 22 47 55" width="1440" src="https://user-images.githubusercontent.com/37238033/147890312-364f2de3-7458-415c-91a9-5724bbbcb188.png">
> 
> @0tuedon I think you should add some padding to the navigation links. You may want to reduce the margin between the two social icons on the top right. You may also want to increase the font size of the 'GetnShare' header on the top left

![Screenshot (284)](https://user-images.githubusercontent.com/90271995/147963351-c07e3913-6ba7-4de2-98ad-d550b5a54c64.png)
This has been done check the lastest commit

2022-01-04 00:36 UTC, Eronmmer approved these changes

2022-01-04 00:36 UTC, merged

2022-01-06 09:09 UTC, 0tuedon commented
@asapconet  how is this design
![Screenshot (288)](https://user-images.githubusercontent.com/90271995/148358180-ccae1640-bd56-460b-88c3-2c227c650295.png)

2022-01-06 09:09 UTC, 0tuedon commented
Please also @Eronmmer  feel free to say what i should change